### ISSUE TITLE
scores_labels_2_eer problem

### ISSUE THREAD

**Issue by jodiesue** [bsxfan/PYLLR#3]
I can't find the scores_labels_2_eer function in pyllr/pav_rocch.py. Could you please tell me where is it?Thanks!

**Comment by bsxfan** [comment]
It has moved and has been renamed slightly for consistency with other similar function names. It is now at:
https://github.com/bsxfan/PYLLR/blob/d157987ba21724bc8de98bcd94c4727751a62e74/pyllr/quick_eval.py#L107

**Comment by jodiesue** [comment]
> It has moved and has been renamed slightly for consistency with other similar function names. It is now at:
> 
> https://github.com/bsxfan/PYLLR/blob/d157987ba21724bc8de98bcd94c4727751a62e74/pyllr/quick_eval.py#L107

Thank you very much!
